#!/usr/bin/env bun
import { run } from '.';

const packageJsonFile = Bun.file('./package.json');

if (!(await packageJsonFile.exists())) {
  throw new Error('No package.json found in current directory');
}
const { scripts } = await packageJsonFile.json();
if (scripts == null) {
  throw new Error('No script definitions found');
}
await run(scripts, Bun.argv.slice(2));
